### ISSUE TITLE
Compatability with WordPress 5?

### ISSUE THREAD

**Issue by ehsan42** [uoe-dlam/ed-lti#30]
Hi,

We are using a cloud hosted version of WordPress hosted by https://campuspress.com/  They have installed and activated the plugin for us but we don’t have any LTI options in our Network Admin > Settings.  I presume these settings should just appear when the plugin is active?  Our WordPress environment is currently on version 5.1.1.

Regards
Ehsan.

**Comment by Sephster** [comment]
Hi @ehsan42 - fantastic that you are trying out our plugin. We have the plugin working on our dev installation which is running 5.2.2 and on our production instance which is running WordPress 4.9 so I believe it should work fine on 5.1.1.

Can you see the two sub menus in the network admin settings? These will be titled _LTI Consumer Keys_ and _LTI Settings_. 

I've included a screenshot of the menus in the image below:

![image](https://user-images.githubusercontent.com/1457058/60352690-47453800-99c0-11e9-9fad-38e98ad86de6.png)

**Comment by ehsan42** [comment]
Hi,

I have checked but don't have the settings.  Are they any other settings that need to be enabled first?

![image](https://user-images.githubusercontent.com/25772828/60353530-1f56d400-99c2-11e9-803b-86c403bc5612.png)

**Comment by Sephster** [comment]
Hi @ehsan42,

To do some quick testing, we just threw up a new multi-site instance with just this plugin installed and it worked for us. The only step you should need to take to see the menu items is to network activate the plugin as shown below:

![image](https://user-images.githubusercontent.com/1457058/60354797-026fd000-99c5-11e9-99a1-fc327adc1e83.png)

Could you confirm that the plugin has been network activated just to rule out this possibility? Failing that, do you have access to any error logs? Thanks for your continued assistance with this.

**Comment by ehsan42** [comment]
Hi @Sephster 

Yes the plugin is network active
![image](https://user-images.githubusercontent.com/25772828/60355514-7fe81000-99c6-11e9-87c9-31ad39cabce1.png)

I have gone to a test site and can active the plugin so its installed
![image](https://user-images.githubusercontent.com/25772828/60355582-a7d77380-99c6-11e9-827e-e20cd439a199.png)

Unfortunately i don't have access to error logs.  I'll ask Campus Press if they can look into this further

**Comment by Sephster** [comment]
If you could ask for error logs, that would be very much appreciated. I'd be keen to resolve any issue that is there for you as we've had a couple of others wanting to use this plugin via CampusPress. Thanks for your help and patience with this. We will hopefully have a resolution for you soon

**Comment by ehsan42** [comment]
Hi @Sephster,
I have spoken to Campus Press and the plugin wasn't network activated which they have done and i now have the settings.  I've followed your instructions steps have setup the settings in WordPress and Moodle and have added the tools as activities into a Moodle course.  To test i created a course with the following users, i was logged in as the teststudent2@ucl.ac.uk account
teststudent2@ucl.ac.uk - course admin role
teststudent3@ucl.ac.uk - student role   

Adding either WordPress Course/Student shows the following screen; I just fill in activity name and click save and return to course

![image](https://user-images.githubusercontent.com/25772828/60727691-69960300-9f36-11e9-8226-2fa570caada5.png)

Then click on WordPress course then creates a WordPress blog for the course and creates an account for the moodle user

![image](https://user-images.githubusercontent.com/25772828/60727043-e2945b00-9f34-11e9-86b4-6a40b5298b84.png)

![image](https://user-images.githubusercontent.com/25772828/60728439-33f21980-9f38-11e9-85d7-360971571a16.png)

So WordPress course seems to work fine but clicking WordPress student in the course i just get the following, reason for this?

Thanks 
Ehsan.

![image](https://user-images.githubusercontent.com/25772828/60729048-b16a5980-9f39-11e9-9b0a-339f160f1751.png)

So just to be clear i presume the WordPress course tool creates a blog for the person who is logged in and the WordPress students tool adds students to the blog?  If you can provide further clarity on exactly how the tools works

**Comment by Sephster** [comment]
Hi @ehsan42,

That's fantastic you have got the plugin working. The course and student links work as follows:

### The Course Blog LTI Link

A single blog, and only one blog, is created when someone clicks on this link. If you are a student, you are added as an author. If you are a lecturer, you are added as an administrator. Everyone works and collaborates on the same blog.

### The Student Blog LTI Link

Each user gets their own blog. When a student clicks on this link, they are given their own blog where they are the administrator and the lecturer of the course is added as an author. No other students are added to this individuals blog unless they are added manually by the administrator of that blog.

If a lecturer clicks the student blog link, as you did in this instance, you are displayed with a list of all individual student blogs associated with a course. In this instance, there are no individual student blogs associated with the course as you have not clicked the student log as a student in Moodle.

If you were to login as _teststudent3_ and click the student blog link, you would have an individual blog created for that student. If you then log out of Moodle, and back in as _teststudent2_, and click the student link, you should now be presented with a list that has _teststudent3's_ blog in it.

I hope this answers your questions but if you have any further queries, please don't hesitate to get in touch and we will be happy to assist further. Thanks!

**Comment by ehsan42** [comment]
Hi @Sephster 

Following your instructions i have logged into Moodle as teststudent3 but when clicking on the student plugin link, i just get get a blank page with just the https://cle-blogs-dev.ucl.ac.uk/index.php url visible however it does create the student account but no site created

![image](https://user-images.githubusercontent.com/25772828/61052063-845af280-a3e2-11e9-9fa1-35ec82d52fe0.png)

regarding the lti tool setting for student, custom parameters is set as blog_type=student, what does this do? how would you normally create a student blog in wordpress?

**Comment by richeduni** [comment]
Hi @ehsan42,

I did some local testing and was successfully able to create student blogs with the latest version of the plugin. However, there was a bug in the plugin that was fixed recently and may be causing the problem in your case. Can you download the latest version of the plugin and try using that instead. Hopefully, that will fix the issue.

The custom parameter blog_type=student ensure that individual blogs are created for students. If the blog type is not set, course blogs are used.

The difference between the two:

If a student clicks a student lti link, a blog will be created for them and they will be made the admin. They get their own individual blog.

If a student clicks a course lti link then they will be added to the course blog as an author. This blog is shared amongst all course students.

**Comment by Sephster** [comment]
Hi @ehsan42 - I was wondering if upgrading to the latest version of the plugin fixed your issue or if there is anything else we can assist you with? Thanks again for providing us with input on the plugin. It really is appreciated!

**Comment by ehsan42** [comment]
Hi @Sephster  - I haven't had a chance yet as I've been busy with our yearly vle upgrades.  Once things calm down I'll have a look further and let you know.  Thanks.

**Comment by Sephster** [comment]
No worries at all @ehsan42 - totally understand what it is like this time of year. If you do need any more assistance, please just reach out. Good luck with the upgrades!

**Comment by ehsan42** [comment]
Hi @Sephster ,

Just an update that I've starting looking into the plugin again.  I'm using the updated code and everything looks fine so far.  I'll be do further testing with the edu blogs team and keep you updated.  Thanks

**Comment by Sephster** [comment]
Hi @ehsan42 - that's great news. Thanks for letting us know. If you require any assistance please do shout. We will leave this issue open a little longer but if don't hear from you we will close it off. Of course, if you do encounter any issues please just post here and we will be happy to reopen it. Thanks very much for the update.
