### ISSUE TITLE
imsiglobal/lti abandoned?

### ISSUE THREAD

**Issue by hliljegren** [uoe-dlam/ed-lti#36]
Hi!

I have no command-line control over our web hotel, but when asked the IT-department to run the installation of the dependencies they got the following back:
Package operations: 1 install, 0 updates, 0 removals
- Installing imsglobal/lti (3.0.2): Downloading (100%)
Package imsglobal/lti is abandoned, you should avoid using it. No replacement was suggested.

Are we missing something?

:-Håkan

**Comment by Sephster** [comment]
Hello @hliljegren - apologies for the delay in responding. I've got in touch with the author for the IMS Global LTI plugin to find out if there is an alternative package we can use. As soon as we get a response, we will update this plugin accordingly.

We are using the latest version of the plugin in our production systems at the moment as we don't believe there are any vulnerabilities with the IMS Global package but understand that this could cause concern and are actively looking into solutions for this at the moment.

I will provide you an update as soon as a I have further information. Thanks for getting in touch.

**Comment by woodwardtw** [comment]
Just wanted to follow up on this. Did it get resolved?

**Comment by Sephster** [comment]
Hi @woodwardtw - sorry this fell through the cracks as I was on shared parental leave. We should be using the ceLTIc/lti-php package instead of the IMSGlobal one. I will work on a new release for this and as long as the APIs are largely the same, I should be able to push this out in the next couple of days. Thanks for your patience.

**Comment by hliljegren** [comment]
Any predictions on when "the next couple of days" will be?

**Comment by Sephster** [comment]
Apologies @hliljegren - I had a look at this the day after my last post. Unfortunately the new LTI library isn't a direct replacement for the old LTI library we use so there isn't an easy migration path.

We will work on this but unfortunately have other projects which are prioritised at present. I don't therefore, have a timescale for putting the migration in place at this time.

**Comment by hliljegren** [comment]
OK, thanks for connecting back!

**Comment by Sephster** [comment]
No worries. Keeping open as we will need to address this at some point

**Comment by Sephster** [comment]
@hliljegren just to update on this, the upgrade to the new LTI package was not straight forward but we have scheduled this work in. I expect this will be completed by the end of April at the latest. Thanks for your patience with this.

**Comment by hliljegren** [comment]
@Sephster Thanks for the update! Tell me if there is anything I can help with!

**Comment by hliljegren** [comment]
Any progress update?

**Comment by Sephster** [comment]
Hi @hliljegren. Thanks for your patience with this. We have  a new plugin created (unfortunately there was no upgrade path) which provides the same functionality and uses the new LTI library. It is currently in testing and as soon as peer reviewed (I expect within the next fortnight) we will release the package and mark this one as archived. Hope that is all ok but if you have any questions please feel free to reach out
